### ISSUE TITLE
ggfortify の文面差し替え

### ISSUE THREAD

**Issue by sinhrks** [kazutan/awesome-ggplot2#1]
CRAN公開しましたので、こちらで差し替えお願いできますか。
### ggfortify
- サイトリンク
  - [GitHub](https://github.com/sinhrks/ggfortify)
  - [CRAN](https://cran.r-project.org/web/packages/ggfortify/index.html)
- 概要
  - 一般的なRパッケージで`ggplot2`をスムーズに使えるようにしたパッケージです
  - カバーしているパッケージが非常に多く、また設定も簡単に行えます
- サンプルコードなど
  - 解説およびサンプルは上記GitHubのリンクを参照してください
  - サンプル: [RPubs - Concepts and Basics of ggfortify](http://rpubs.com/sinhrks/basics)
- インストール
  - CRANよりインストール

``` R
install.packages("ggfortify", dependencies=TRUE)
```

**Comment by kazutan** [comment]
ありがとうございます。差し替えます。

**Comment by sinhrks** [comment]
Thx!
